name: mkdocs
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libcxx=19.1.7
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.3
  - python=3.13.5
  - python_abi=3.13
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - addbioschemas==1.0.2
      - anyio==4.12.0
      - babel==2.17.0
      - backrefs==6.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - essentials==1.1.9
      - essentials-openapi==1.3.0
      - ghp-import==2.1.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jinja2==3.1.6
      - latexcodec==3.0.1
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mkdocs==1.6.1
      - mkdocs-bibtex==4.4.0
      - mkdocs-get-deps==0.2.0
      - mkdocs-material==9.7.1
      - mkdocs-material-extensions==1.3.1
      - mkdocs-video==1.5.0
      - neoteroi-mkdocs==1.2.0
      - packaging==25.0
      - paginate==0.5.7
      - pathspec==0.12.1
      - platformdirs==4.5.1
      - pybtex==0.25.1
      - pygments==2.19.2
      - pymdown-extensions==10.19.1
      - pypandoc==1.16.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyyaml-env-tag==1.1
      - regex==2025.11.3
      - requests==2.32.5
      - responses==0.25.8
      - rich==14.2.0
      - six==1.17.0
      - urllib3==2.6.2
      - ushlex==0.99.1
      - validators==0.35.0
      - watchdog==6.0.0
